<a href="https://colab.research.google.com/github/myra349/vistarnetra/blob/main/FEEDBACKANALYSIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Faculty Feedback Multi-Domain Weighted Evaluation Algorithm (FF-MDWEA)

In [ ]:
import pandas as pd
import random
import numpy as np

In [ ]:
faculty_ids = [f"F{100+i}" for i in range(20)]

subjects = [
    "Python", "AI", "ML", "Cloud", "DSA",
    "DBMS", "Networks", "Cybersecurity", "OS", "Maths",
    "Data Science", "Big Data", "IOT", "Robotics", "Deep Learning",
    "NLP", "Compiler Design", "Web Dev", "Java", "C Programming"
]

faculty_subject_map = {faculty_ids[i]: subjects[i] for i in range(20)}
faculty_subject_map

{'F100': 'Python',
 'F101': 'AI',
 'F102': 'ML',
 'F103': 'Cloud',
 'F104': 'DSA',
 'F105': 'DBMS',
 'F106': 'Networks',
 'F107': 'Cybersecurity',
 'F108': 'OS',
 'F109': 'Maths',
 'F110': 'Data Science',
 'F111': 'Big Data',
 'F112': 'IOT',
 'F113': 'Robotics',
 'F114': 'Deep Learning',
 'F115': 'NLP',
 'F116': 'Compiler Design',
 'F117': 'Web Dev',
 'F118': 'Java',
 'F119': 'C Programming'}

In [ ]:
student_ids = [f"S{1000+i}" for i in range(100)]

In [ ]:
domains = [
    "concept_explanation",
    "real_life_examples",
    "pace",
    "doubt_handling",
    "clarity",
    "language_clarity",
    "interaction",
    "communication",
    "knowledge_depth",
    "industry_relevance",
    "updated_content",
    "time_management",
    "discipline_control",
    "ppt_quality",
    "assignment_quality"
]

In [ ]:
positive_comments = [
    "Excellent teaching style",
    "Very good explanation",
    "Super clarity in concepts",
    "Helpful and supportive faculty",
    "Easy to understand classes",
    "Interactive class atmosphere",
    "Explains concepts very clearly",
    "Good pace and proper examples",
    "Always encourages doubts",
    "Very friendly and approachable",
    "Makes even tough topics easy",
    "Uses real-life examples perfectly",
    "Good clarity and depth",
    "Well structured teaching",
    "Very calm and patient",
    "Provides extra materials",
    "Responds to doubts immediately",
    "Superb teaching quality",
    "Motivates students very well",
    "Best faculty for this subject",
    "Highly knowledgeable",
    "Gives practical insights",
    "Always energetic and positive",
    "Amazing content delivery",
    "Top-class teaching",
    "Covers syllabus properly",
    "Always available for help",
    "Strong command on subject",
    "Very dedicated teaching style",
    "Creates interest in subject",
    "Gives good assignments",
    "Uses examples beautifully",
    "Makes learning fun",
    "Very professional and clear",
    "Explains slowly and clearly",
    "Great board explanation",
    "Good at simplifying concepts",
    "Provides quality notes",
    "Uses visuals effectively",
    "Outstanding teaching quality",
    "Always punctual and consistent",
    "Very respectful and humble",
    "Encourages participation",
    "Explains multiple times if needed",
    "Relates theory with industry",
    "Perfect teaching pace",
    "Very confident lecturer",
    "Creates a positive environment"
]

In [ ]:
neutral_comments = [
    "Class is okay",
    "Average teaching style",
    "Sometimes good, sometimes confusing",
    "Normal class experience",
    "Satisfactory explanation",
    "Standard teaching method",
    "Could add more examples",
    "Sometimes pace is fast",
    "Sometimes pace is slow",
    "Content is fine",
    "Nothing exceptional",
    "PPTs are okay",
    "Needs more interaction",
    "Teaching is decent",
    "Can improve delivery method",
    "Materials are okay",
    "Explains but lacks depth",
    "Adequate teaching",
    "Neutral experience overall",
    "Not too good, not too bad",
    "Sometimes engaging",
    "Sometimes monotonous",
    "Assignment quality is fine",
    "Classroom atmosphere is alright",
    "Could focus more on basics",
    "Timing management is okay",
    "Sometimes repeats same points",
    "Class is manageable",
    "Needs slight improvement",
    "Better than average",
    "Can improve communication",
    "Subject knowledge is good but delivery average",
    "Sometimes difficult to follow",
    "Neither interactive nor boring",
    "Good explanations sometimes",
    "Teaching is moderate",
    "Presentation can be better",
    "Regular class, nothing special",
    "Pace is acceptable",
    "Explains but could improve clarity",
    "Class engagement is average",
    "Effort is visible",
    "Could improve examples",
    "Teaching can be more interesting",
    "Communication is okay",
    "Explains topics adequately",
    "Needs more practice problems",
    "Could improve board usage",
    "Neutral feedback overall"
]

In [ ]:
neutral_comments = [
    "Class is okay",
    "Average teaching style",
    "Sometimes good, sometimes confusing",
    "Normal class experience",
    "Satisfactory explanation",
    "Standard teaching method",
    "Could add more examples",
    "Sometimes pace is fast",
    "Sometimes pace is slow",
    "Content is fine",
    "Nothing exceptional",
    "PPTs are okay",
    "Needs more interaction",
    "Teaching is decent",
    "Can improve delivery method",
    "Materials are okay",
    "Explains but lacks depth",
    "Adequate teaching",
    "Neutral experience overall",
    "Not too good, not too bad",
    "Sometimes engaging",
    "Sometimes monotonous",
    "Assignment quality is fine",
    "Classroom atmosphere is alright",
    "Could focus more on basics",
    "Timing management is okay",
    "Sometimes repeats same points",
    "Class is manageable",
    "Needs slight improvement",
    "Better than average",
    "Can improve communication",
    "Subject knowledge is good but delivery average",
    "Sometimes difficult to follow",
    "Neither interactive nor boring",
    "Good explanations sometimes",
    "Teaching is moderate",
    "Presentation can be better",
    "Regular class, nothing special",
    "Pace is acceptable",
    "Explains but could improve clarity",
    "Class engagement is average",
    "Effort is visible",
    "Could improve examples",
    "Teaching can be more interesting",
    "Communication is okay",
    "Explains topics adequately",
    "Needs more practice problems",
    "Could improve board usage",
    "Neutral feedback overall"
]

In [ ]:
negative_comments = [
    "Poor teaching style",
    "Concepts are not clear",
    "Very confusing explanations",
    "Unhelpful and unsupportive faculty",
    "Difficult to understand classes",
    "Lack of interaction in class",
    "Does not explain concepts clearly",
    "Too fast pace, no proper examples",
    "Discourages doubts",
    "Unfriendly and unapproachable",
    "Makes simple topics difficult",
    "Rarely uses real-life examples",
    "Poor clarity and superficial depth",
    "Disorganized teaching structure",
    "Impatient and easily agitated",
    "Does not provide extra materials",
    "Ignores doubts or responds late",
    "Terrible teaching quality",
    "Demotivates students",
    "Worst faculty for this subject",
    "Lacks knowledge depth",
    "No practical insights",
    "Always dull and negative",
    "Unimpressive content delivery",
    "Substandard teaching",
    "Does not cover syllabus properly",
    "Never available for help",
    "Weak command on subject",
    "Very uninterested teaching style",
    "Fails to create interest in subject",
    "Gives useless assignments",
    "Examples are poorly chosen",
    "Makes learning boring",
    "Unprofessional and unclear",
    "Explains too fast and unclearly",
    "Bad board explanation",
    "Struggles at simplifying concepts",
    "Provides low-quality notes",
    "Uses visuals ineffectively",
    "Awful teaching quality",
    "Always late and inconsistent",
    "Very disrespectful and arrogant",
    "Discourages participation",
    "Never explains multiple times",
    "Fails to relate theory with industry",
    "Awkward teaching pace",
    "Very unconfident lecturer",
    "Creates a negative environment"
]

rows = []

for fac in faculty_ids:

    subject = faculty_subject_map[fac]  # faculty teaches only this subject

    for stu in student_ids:

        # 15 domain ratings (2 to 5 realistic)
        domain_scores = [random.randint(2,5) for _ in range(15)]

        avg_rating = sum(domain_scores) / 15

        # Comment based on avg rating
        if avg_rating >= 4:
            fb = random.choice(positive_comments)
        elif avg_rating >= 3:
            fb = random.choice(neutral_comments)
        else:
            fb = random.choice(negative_comments)

        row = [stu, fac, subject] + domain_scores + [fb]
        rows.append(row)

columns = ["student_id", "faculty_id", "subject"] + domains + ["feedback_comment"]
df_feedback = pd.DataFrame(rows, columns=columns)

df_feedback.head()

NameError: name 'negative_comments' is not defined

In [ ]:
negative_comments = [
    "Poor teaching style",
    "Concepts are not clear",
    "Very confusing explanations",
    "Unhelpful and unsupportive faculty",
    "Difficult to understand classes",
    "Lack of interaction in class",
    "Does not explain concepts clearly",
    "Too fast pace, no proper examples",
    "Discourages doubts",
    "Unfriendly and unapproachable",
    "Makes simple topics difficult",
    "Rarely uses real-life examples",
    "Poor clarity and superficial depth",
    "Disorganized teaching structure",
    "Impatient and easily agitated",
    "Does not provide extra materials",
    "Ignores doubts or responds late",
    "Terrible teaching quality",
    "Demotivates students",
    "Worst faculty for this subject",
    "Lacks knowledge depth",
    "No practical insights",
    "Always dull and negative",
    "Unimpressive content delivery",
    "Substandard teaching",
    "Does not cover syllabus properly",
    "Never available for help",
    "Weak command on subject",
    "Very uninterested teaching style",
    "Fails to create interest in subject",
    "Gives useless assignments",
    "Examples are poorly chosen",
    "Makes learning boring",
    "Unprofessional and unclear",
    "Explains too fast and unclearly",
    "Bad board explanation",
    "Struggles at simplifying concepts",
    "Provides low-quality notes",
    "Uses visuals ineffectively",
    "Awful teaching quality",
    "Always late and inconsistent",
    "Very disrespectful and arrogant",
    "Discourages participation",
    "Never explains multiple times",
    "Fails to relate theory with industry",
    "Awkward teaching pace",
    "Very unconfident lecturer",
    "Creates a negative environment"
]

rows = []

for fac in faculty_ids:

    subject = faculty_subject_map[fac]  # faculty teaches only this subject

    for stu in student_ids:

        # 15 domain ratings (2 to 5 realistic)
        domain_scores = [random.randint(2,5) for _ in range(15)]

        avg_rating = sum(domain_scores) / 15

        # Comment based on avg rating
        if avg_rating >= 4:
            fb = random.choice(positive_comments)
        elif avg_rating >= 3:
            fb = random.choice(neutral_comments)
        else:
            fb = random.choice(negative_comments)

        row = [stu, fac, subject] + domain_scores + [fb]
        rows.append(row)

columns = ["student_id", "faculty_id", "subject"] + domains + ["feedback_comment"]
df_feedback = pd.DataFrame(rows, columns=columns)

df_feedback.head()

,student_id,faculty_id,subject,concept_explanation,real_life_examples,pace,doubt_handling,clarity,language_clarity,interaction,communication,knowledge_depth,industry_relevance,updated_content,time_management,discipline_control,ppt_quality,assignment_quality,feedback_comment
0,S1000,F100,Python,4,4,4,3,4,2,5,4,4,4,5,4,3,5,5,Responds to doubts immediately
1,S1001,F100,Python,3,4,5,4,2,3,3,2,2,2,4,3,2,2,3,Fails to relate theory with industry
2,S1002,F100,Python,5,5,3,4,2,3,3,4,5,3,4,4,5,2,3,Could improve board usage
3,S1003,F100,Python,3,2,4,5,2,5,5,3,4,2,4,4,4,3,4,"Not too good, not too bad"
4,S1004,F100,Python,3,4,4,4,2,2,3,5,5,4,2,5,4,3,3,Class engagement is average

In [ ]:
df_feedback.to_csv("faculty_feedback_2000.csv", index=False)
df_feedback.shape

(2000, 19)

In [ ]:
from google.colab import files
files.download("/content/faculty_feedback_2000.csv")

In [ ]:
import pandas as pd

df = pd.read_csv("/content/faculty_feedback_2000.csv")
df.head()

,student_id,faculty_id,subject,concept_explanation,real_life_examples,pace,doubt_handling,clarity,language_clarity,interaction,communication,knowledge_depth,industry_relevance,updated_content,time_management,discipline_control,ppt_quality,assignment_quality,feedback_comment
0,S1000,F100,Python,4,4,4,3,4,2,5,4,4,4,5,4,3,5,5,Responds to doubts immediately
1,S1001,F100,Python,3,4,5,4,2,3,3,2,2,2,4,3,2,2,3,Fails to relate theory with industry
2,S1002,F100,Python,5,5,3,4,2,3,3,4,5,3,4,4,5,2,3,Could improve board usage
3,S1003,F100,Python,3,2,4,5,2,5,5,3,4,2,4,4,4,3,4,"Not too good, not too bad"
4,S1004,F100,Python,3,4,4,4,2,2,3,5,5,4,2,5,4,3,3,Class engagement is average

In [ ]:
domains = [
    "concept_explanation", "real_life_examples", "pace", "doubt_handling",
    "clarity", "language_clarity", "interaction", "communication",
    "knowledge_depth", "industry_relevance", "updated_content",
    "time_management", "discipline_control", "ppt_quality",
    "assignment_quality"
]

In [ ]:
faculty_domain_avg = df.groupby("faculty_id")[domains].mean()
faculty_domain_avg

,concept_explanation,real_life_examples,pace,doubt_handling,clarity,language_clarity,interaction,communication,knowledge_depth,industry_relevance,updated_content,time_management,discipline_control,ppt_quality,assignment_quality
faculty_id,,,,,,,,,,,,,,,
F100,3.56,3.62,3.63,3.51,3.60,3.35,3.63,3.48,3.74,3.44,3.48,3.58,3.55,3.34,3.51
F101,3.64,3.47,3.51,3.59,3.47,3.61,3.49,3.68,3.67,3.59,3.45,3.61,3.58,3.44,3.53
F102,3.39,3.62,3.55,3.62,3.61,3.68,3.74,3.50,3.70,3.56,3.67,3.60,3.47,3.38,3.49
F103,3.51,3.57,3.41,3.71,3.62,3.57,3.76,3.64,3.43,3.64,3.54,3.58,3.59,3.67,3.51
F104,3.24,3.45,3.62,3.58,3.53,3.45,3.52,3.63,3.37,3.34,3.46,3.69,3.71,3.37,3.53
F105,3.69,3.65,3.29,3.52,3.58,3.43,3.56,3.41,3.51,3.53,3.55,3.64,3.44,3.49,3.66
F106,3.51,3.52,3.50,3.56,3.36,3.56,3.42,3.83,3.50,3.64,3.64,3.51,3.21,3.62,3.66
F107,3.68,3.49,3.61,3.46,3.49,3.43,3.41,3.70,3.52,3.35,3.49,3.61,3.61,3.63,3.53
F108,3.35,3.46,3.53,3.66,3.45,3.43,3.36,3.51,3.54,3.54,3.65,3.37,3.42,3.50,3.58
F109,3.47,3.38,3.76,3.55,3.55,3.57,3.54,3.36,3.49,3.53,3.65,3.56,3.32,3.53,3.64
F110,3.48,3.49,3.49,3.61,3.40,3.58,3.52,3.45,3.64,3.44,3.50,3.38,3.56,3.63,3.52
F111,3.65,3.51,3.67,3.62,3.18,3.40,3.57,3.51,3.36,3.51,3.38,3.44,3.50,3.48,3.72
F112,3.65,3.51,3.55,3.39,3.58,3.49,3.50,3.39,3.54,3.40,3.51,3.37,3.54,3.50,3.49
F113,3.65,3.39,3.22,3.60,3.36,3.60,3.42,3.46,3.32,3.50,3.41,3.54,3.53,3.35,3.34
F114,3.51,3.48,3.39,3.46,3.63,3.63,3.71,3.51,3.52,3.40,3.54,3.57,3.60,3.60,3.49
F115,3.50,3.25,3.51,3.51,3.42,3.45,3.41,3.66,3.45,3.35,3.43,3.41,3.49,3.43,3.57
F116,3.51,3.67,3.43,3.30,3.63,3.66,3.61,3.62,3.64,3.59,3.62,3.43,3.35,3.58,3.38
F117,3.50,3.36,3.46,3.50,3.54,3.57,3.69,3.57,3.57,3.48,3.51,3.62,3.60,3.42,3.48
F118,3.49,3.49,3.45,3.40,3.56,3.53,3.67,3.46,3.44,3.62,3.62,3.51,3.45,3.47,3.65
F119,3.52,3.67,3.25,3.37,3.42,3.51,3.47,3.47,3.62,3.53,3.55,3.66,3.37,3.65,3.68

In [ ]:
faculty_scores = faculty_domain_avg.mean(axis=1).sort_values(ascending=False)
faculty_scores

faculty_id
F103    3.583333
F102    3.572000
F101    3.555333
F114    3.536000
F106    3.536000
F116    3.534667
F100    3.534667
F107    3.534000
F105    3.530000
F109    3.526667
F117    3.524667
F118    3.520667
F119    3.516000
F110    3.512667
F111    3.500000
F104    3.499333
F112    3.494000
F108    3.490000
F115    3.456000
F113    3.446000
dtype: float64

In [ ]:
import plotly.express as px

fig = px.bar(
    x=faculty_scores.index,
    y=faculty_scores.values,
    title="🏆 Faculty Overall Performance Score",
    labels={"x": "Faculty", "y": "Score"},
    color=faculty_scores.values,
    color_continuous_scale="Greens"
)
fig.update_traces(text=faculty_scores.values, textposition="outside")
fig.show()

In [ ]:
import plotly.graph_objects as go

def plot_faculty_radar(faculty_id):
    values = faculty_domain_avg.loc[faculty_id].values
    labels = domains

    fig = go.Figure()

    fig.add_trace(go.Scatterpolar(
        r=values,
        theta=labels,
        fill='toself',
        name=f"Performance Radar — {faculty_id}"
    ))

    fig.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[1,5])),
        showlegend=False,
        title=f"🎯 Faculty Strength Radar: {faculty_id}"
    )

    fig.show()

# Example usage
plot_faculty_radar("F113")

In [ ]:
avg_domain_scores = df[domains].mean().sort_values(ascending=True)

fig = px.bar(
    y=avg_domain_scores.index,
    x=avg_domain_scores.values,
    title="📚 Avg Rating per Domain (All Faculty)",
    orientation='h',
    color=avg_domain_scores.values,
    color_continuous_scale="Blues"
)
fig.show()

In [ ]:
top5 = faculty_scores.head(5)
bottom5 = faculty_scores.tail(5)

print("🏆 Top 5 Faculty:\n", top5)
print("\n⚠️ Bottom 5 Faculty:\n", bottom5)

🏆 Top 5 Faculty:
 faculty_id
F103    3.583333
F102    3.572000
F101    3.555333
F114    3.536000
F106    3.536000
dtype: float64

⚠️ Bottom 5 Faculty:
 faculty_id
F104    3.499333
F112    3.494000
F108    3.490000
F115    3.456000
F113    3.446000
dtype: float64

In [ ]:
def faculty_suggestions(faculty_id):
    data = faculty_domain_avg.loc[faculty_id]
    weak = data[data < 3.0]

    print(f"\n📌 Suggestions for {faculty_id}:\n")
    if len(weak)==0:
        print("✔ No improvements required. This faculty is performing well.")
    else:
        for dom in weak.index:
            print(f"⚠ {dom.replace('_',' ').title()} needs improvement")

faculty_suggestions("F104")

📌 Suggestions for F104:

✔ No improvements required. This faculty is performing well.

In [ ]:
print("\n🎯 TOTAL SUMMARY")
print("Number of Faculty:", df['faculty_id'].nunique())
print("Feedback Count   :", len(df))
print("Best Faculty      :", faculty_scores.idxmax())
print("Weakest Faculty   :", faculty_scores.idxmin())
print("Strongest Domain  :", avg_domain_scores.idxmax())
print("Weakest Domain    :", avg_domain_scores.idxmin())

🎯 TOTAL SUMMARY
Number of Faculty: 20
Feedback Count   : 2000
Best Faculty      : F103
Weakest Faculty   : F113
Strongest Domain  : interaction
Weakest Domain    : pace

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

summary_fig = make_subplots(
    rows=2, cols=3,
    specs=[[{"type": "indicator"}]*3,
           [{"type": "indicator"}]*3],
    subplot_titles=("Faculty Count", "Feedback Count", "Best Faculty",
                    "Weakest Faculty", "Strongest Domain", "Weakest Domain")
)

# 1 Faculty Count
summary_fig.add_trace(go.Indicator(
    mode="number",
    value=df['faculty_id'].nunique(),
    title="Number of Faculty",
    number={"font":{"size":40, "color":"#10b981"}}
), row=1, col=1)

# 2 Feedback Count
summary_fig.add_trace(go.Indicator(
    mode="number",
    value=len(df),
    title="Total Feedback Entries",
    number={"font":{"size":40, "color":"#3b82f6"}}
), row=1, col=2)

# 3 Best Faculty
summary_fig.add_trace(go.Indicator(
    mode="number+delta",
    value=faculty_scores.max(),
    delta={"reference":faculty_scores.min(), "increasing":{"color":"green"}},
    title=f"Best Faculty ({faculty_scores.idxmax()})",
    number={"font":{"size":40, "color":"#22c55e"}}
), row=1, col=3)

# 4 Weakest Faculty
summary_fig.add_trace(go.Indicator(
    mode="number+delta",
    value=faculty_scores.min(),
    delta={"reference":faculty_scores.max(), "decreasing":{"color":"red"}},
    title=f"Weakest Faculty ({faculty_scores.idxmin()})",
    number={"font":{"size":40, "color":"#ef4444"}}
), row=2, col=1)

# 5 Strongest Domain
strong_dom = avg_domain_scores.idxmax()
summary_fig.add_trace(go.Indicator(
    mode="number",
    value=avg_domain_scores.max(),
    title=f"Strongest Domain ({strong_dom.replace('_',' ').title()})",
    number={"font":{"size":40, "color":"#0ea5e9"}}
), row=2, col=2)

# 6 Weakest Domain
weak_dom = avg_domain_scores.idxmin()
summary_fig.add_trace(go.Indicator(
    mode="number",
    value=avg_domain_scores.min(),
    title=f"Weakest Domain ({weak_dom.replace('_',' ').title()})",
    number={"font":{"size":40, "color":"#f97316"}}
), row=2, col=3)

summary_fig.update_layout(height=700, width=1200, title_text="🔥 OVERALL FEEDBACK SUMMARY DASHBOARD")
summary_fig.show()

In [ ]:
suggestion_map = {
    "concept_explanation": "Improve clarity by breaking topics into smaller units and giving more structured explanations.",
    "real_life_examples": "Add more real-world examples and case studies to make concepts relatable.",
    "pace": "Try slowing down the teaching pace and pause after each concept for better understanding.",
    "doubt_handling": "Encourage more questions and allocate dedicated doubt-solving time.",
    "clarity": "Use board/PPT highlighting to improve clarity and avoid rushed explanations.",
    "language_clarity": "Improve pronunciation and reduce filler words for better comprehension.",
    "interaction": "Engage students through polls, questions, and small discussions.",
    "communication": "Focus on tone modulation and make communication more student-friendly.",
    "knowledge_depth": "Include advanced insights and practical scenarios to show deeper understanding.",
    "industry_relevance": "Connect topics to modern industry tools, trends, and technologies.",
    "updated_content": "Update lecture content to latest syllabus revision and new methodologies.",
    "time_management": "Maintain strict timing for topics and avoid spending too long on one part.",
    "discipline_control": "Strengthen classroom control by using positive reinforcement strategies.",
    "ppt_quality": "Improve PPT readability, reduce text, and add diagrams and flowcharts.",
    "assignment_quality": "Design assignments that are application-based and include real-world tasks."
}

In [ ]:
def generate_suggestions_for_faculty(faculty_id):
    fac = faculty_domain_avg.loc[faculty_id]
    weak_domains = fac[fac < 3.0]

    print(f"\n📝 AUTO-GENERATED IMPROVEMENT SUGGESTIONS FOR {faculty_id}:\n")

    if len(weak_domains) == 0:
        print("✔ All teaching domains are strong. No improvement required.")
        return

    for domain in weak_domains.index:
        print(f"⚠ {domain.replace('_',' ').title()}:")
        print("➡", suggestion_map[domain])
        print()

In [ ]:
generate_suggestions_for_faculty("F104")

In [ ]:
import plotly.graph_objects as go

def compare_faculty_domain(faculty_id):
    fac_scores = faculty_domain_avg.loc[faculty_id].values
    avg_scores = faculty_domain_avg.mean().values

    fig = go.Figure()

    # Faculty Line
    fig.add_trace(go.Scatter(
        x=domains,
        y=fac_scores,
        mode='lines+markers',
        name=f'{faculty_id} Scores',
        line=dict(color='green', width=4),
        marker=dict(size=8)
    ))

    # Institute Average Line
    fig.add_trace(go.Scatter(
        x=domains,
        y=avg_scores,
        mode='lines+markers',
        name='Institute Average',
        line=dict(color='blue', width=3, dash='dash'),
        marker=dict(size=8)
    ))

    fig.update_layout(
        title=f"📊 Domain-wise Comparison: {faculty_id} vs Institute Average",
        xaxis_title="Teaching Domains",
        yaxis_title="Rating",
        width=1200,
        height=500
    )

    fig.show()

# Example
compare_faculty_domain("F119")

In [ ]:
import pandas as pd
import numpy as np

# df is your feedback dataframe
# faculty_domain_avg is computed earlier
# domains list already exists

df_feedback = df.copy()   # rename for clarity

In [ ]:
# Calculate overall SD of ratings across all 15 domains
all_ratings = df_feedback[domains].values.flatten()

std_dev = np.std(all_ratings)
RSA = 1 - (std_dev / 5)

print("📌 Rating Stability Accuracy (RSA):", round(RSA * 100, 2), "%")

📌 Rating Stability Accuracy (RSA): 77.66 %

In [ ]:
def cronbach_alpha(df):
    df_scores = df[domains]
    item_vars = df_scores.var(axis=0, ddof=1)
    total_var = df_scores.sum(axis=1).var(ddof=1)
    k = df_scores.shape[1]
    alpha = (k / (k - 1)) * (1 - item_vars.sum() / total_var)
    return alpha

alpha = cronbach_alpha(df_feedback)
print("📌 Domain Reliability (Cronbach Alpha):", round(alpha * 100, 2), "%")

📌 Domain Reliability (Cronbach Alpha): -6.49 %

In [ ]:
faculty_scores = faculty_domain_avg.mean(axis=1)
inst_avg = faculty_scores.mean()

deviation = abs(faculty_scores - inst_avg).mean()
FEA = 1 - (deviation / 5)

print("📌 Faculty Evaluation Accuracy (FEA):", round(FEA * 100, 2), "%")

📌 Faculty Evaluation Accuracy (FEA): 99.51 %

In [ ]:
!pip install textblob
from textblob import TextBlob

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.1)

In [ ]:
def sentiment(text):
    if pd.isna(text) or text.strip() == "":
        return 0
    return TextBlob(text).sentiment.polarity

df_feedback["sentiment"] = df_feedback["feedback_comment"].apply(sentiment)

In [ ]:
aligned = 0

for _, row in df_feedback.iterrows():
    rat = np.mean([row[d] for d in domains])  # avg domain score
    sent = row["sentiment"]

    if sent > 0 and rat >= 3:     # positive comment ⇒ high rating
        aligned += 1
    elif sent < 0 and rat < 3:   # negative comment ⇒ low rating
        aligned += 1
    elif -0.1 <= sent <= 0.1 and 2.5 <= rat <= 3.5:  # neutral ⇒ mid rating
        aligned += 1

SRA = aligned / len(df_feedback)

print("📌 Sentiment–Rating Alignment Accuracy (SRA):", round(SRA * 100, 2), "%")

📌 Sentiment–Rating Alignment Accuracy (SRA): 70.0 %

In [ ]:
overall_accuracy = (RSA + alpha + FEA + SRA) / 4

print("\n🎯 OVERALL SYSTEM ACCURACY:", round(overall_accuracy * 100, 2), "%")

🎯 OVERALL SYSTEM ACCURACY: 60.17 %

In [ ]:
df_feedback.to_csv("faculty_feedback_2000.csv", index=False)
df_feedback.shape

(2000, 20)

In [ ]:
from google.colab import files
files.download("/content/faculty_feedback_2000.csv")

In [ ]:
import pandas as pd

df = pd.read_csv("/content/faculty_feedback_2000.csv")
df.head()

,student_id,faculty_id,subject,concept_explanation,real_life_examples,pace,doubt_handling,clarity,language_clarity,interaction,communication,knowledge_depth,industry_relevance,updated_content,time_management,discipline_control,ppt_quality,assignment_quality,feedback_comment,sentiment
0,S1000,F100,Python,4,4,4,3,4,2,5,4,4,4,5,4,3,5,5,Responds to doubts immediately,0.000000e+00
1,S1001,F100,Python,3,4,5,4,2,3,3,2,2,2,4,3,2,2,3,Fails to relate theory with industry,-5.000000e-01
2,S1002,F100,Python,5,5,3,4,2,3,3,4,5,3,4,4,5,2,3,Could improve board usage,0.000000e+00
3,S1003,F100,Python,3,2,4,5,2,5,5,3,4,2,4,4,4,3,4,"Not too good, not too bad",5.551115e-17
4,S1004,F100,Python,3,4,4,4,2,2,3,5,5,4,2,5,4,3,3,Class engagement is average,-1.500000e-01

In [ ]:
domains = [
    "concept_explanation", "real_life_examples", "pace", "doubt_handling",
    "clarity", "language_clarity", "interaction", "communication",
    "knowledge_depth", "industry_relevance", "updated_content",
    "time_management", "discipline_control", "ppt_quality",
    "assignment_quality"
]

In [ ]:
faculty_domain_avg = df.groupby("faculty_id")[domains].mean()
faculty_domain_avg

,concept_explanation,real_life_examples,pace,doubt_handling,clarity,language_clarity,interaction,communication,knowledge_depth,industry_relevance,updated_content,time_management,discipline_control,ppt_quality,assignment_quality
faculty_id,,,,,,,,,,,,,,,
F100,3.56,3.62,3.63,3.51,3.60,3.35,3.63,3.48,3.74,3.44,3.48,3.58,3.55,3.34,3.51
F101,3.64,3.47,3.51,3.59,3.47,3.61,3.49,3.68,3.67,3.59,3.45,3.61,3.58,3.44,3.53
F102,3.39,3.62,3.55,3.62,3.61,3.68,3.74,3.50,3.70,3.56,3.67,3.60,3.47,3.38,3.49
F103,3.51,3.57,3.41,3.71,3.62,3.57,3.76,3.64,3.43,3.64,3.54,3.58,3.59,3.67,3.51
F104,3.24,3.45,3.62,3.58,3.53,3.45,3.52,3.63,3.37,3.34,3.46,3.69,3.71,3.37,3.53
F105,3.69,3.65,3.29,3.52,3.58,3.43,3.56,3.41,3.51,3.53,3.55,3.64,3.44,3.49,3.66
F106,3.51,3.52,3.50,3.56,3.36,3.56,3.42,3.83,3.50,3.64,3.64,3.51,3.21,3.62,3.66
F107,3.68,3.49,3.61,3.46,3.49,3.43,3.41,3.70,3.52,3.35,3.49,3.61,3.61,3.63,3.53
F108,3.35,3.46,3.53,3.66,3.45,3.43,3.36,3.51,3.54,3.54,3.65,3.37,3.42,3.50,3.58
F109,3.47,3.38,3.76,3.55,3.55,3.57,3.54,3.36,3.49,3.53,3.65,3.56,3.32,3.53,3.64
F110,3.48,3.49,3.49,3.61,3.40,3.58,3.52,3.45,3.64,3.44,3.50,3.38,3.56,3.63,3.52
F111,3.65,3.51,3.67,3.62,3.18,3.40,3.57,3.51,3.36,3.51,3.38,3.44,3.50,3.48,3.72
F112,3.65,3.51,3.55,3.39,3.58,3.49,3.50,3.39,3.54,3.40,3.51,3.37,3.54,3.50,3.49
F113,3.65,3.39,3.22,3.60,3.36,3.60,3.42,3.46,3.32,3.50,3.41,3.54,3.53,3.35,3.34
F114,3.51,3.48,3.39,3.46,3.63,3.63,3.71,3.51,3.52,3.40,3.54,3.57,3.60,3.60,3.49
F115,3.50,3.25,3.51,3.51,3.42,3.45,3.41,3.66,3.45,3.35,3.43,3.41,3.49,3.43,3.57
F116,3.51,3.67,3.43,3.30,3.63,3.66,3.61,3.62,3.64,3.59,3.62,3.43,3.35,3.58,3.38
F117,3.50,3.36,3.46,3.50,3.54,3.57,3.69,3.57,3.57,3.48,3.51,3.62,3.60,3.42,3.48
F118,3.49,3.49,3.45,3.40,3.56,3.53,3.67,3.46,3.44,3.62,3.62,3.51,3.45,3.47,3.65
F119,3.52,3.67,3.25,3.37,3.42,3.51,3.47,3.47,3.62,3.53,3.55,3.66,3.37,3.65,3.68

In [ ]:
faculty_scores = faculty_domain_avg.mean(axis=1).sort_values(ascending=False)
faculty_scores

faculty_id
F103    3.583333
F102    3.572000
F101    3.555333
F114    3.536000
F106    3.536000
F116    3.534667
F100    3.534667
F107    3.534000
F105    3.530000
F109    3.526667
F117    3.524667
F118    3.520667
F119    3.516000
F110    3.512667
F111    3.500000
F104    3.499333
F112    3.494000
F108    3.490000
F115    3.456000
F113    3.446000
dtype: float64

In [ ]:
import plotly.express as px

fig = px.bar(
    x=faculty_scores.index,
    y=faculty_scores.values,
    title="🏆 Faculty Overall Performance Score",
    labels={"x": "Faculty", "y": "Score"},
    color=faculty_scores.values,
    color_continuous_scale="Greens"
)
fig.update_traces(text=faculty_scores.values, textposition="outside")
fig.show()

In [ ]:
import plotly.graph_objects as go

def plot_faculty_radar(faculty_id):
    values = faculty_domain_avg.loc[faculty_id].values
    labels = domains

    fig = go.Figure()

    fig.add_trace(go.Scatterpolar(
        r=values,
        theta=labels,
        fill='toself',
        name=f"Performance Radar — {faculty_id}"
    ))

    fig.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[1,5])),
        showlegend=False,
        title=f"🎯 Faculty Strength Radar: {faculty_id}"
    )

    fig.show()

# Example usage
plot_faculty_radar("F113")

In [ ]:
avg_domain_scores = df[domains].mean().sort_values(ascending=True)

fig = px.bar(
    y=avg_domain_scores.index,
    x=avg_domain_scores.values,
    title="📚 Avg Rating per Domain (All Faculty)",
    orientation='h',
    color=avg_domain_scores.values,
    color_continuous_scale="Blues"
)
fig.show()

In [ ]:
top5 = faculty_scores.head(5)
bottom5 = faculty_scores.tail(5)

print("🏆 Top 5 Faculty:\n", top5)
print("\n⚠️ Bottom 5 Faculty:\n", bottom5)

🏆 Top 5 Faculty:
 faculty_id
F103    3.583333
F102    3.572000
F101    3.555333
F114    3.536000
F106    3.536000
dtype: float64

⚠️ Bottom 5 Faculty:
 faculty_id
F104    3.499333
F112    3.494000
F108    3.490000
F115    3.456000
F113    3.446000
dtype: float64

In [ ]:
def faculty_suggestions(faculty_id):
    data = faculty_domain_avg.loc[faculty_id]
    weak = data[data < 3.0]

    print(f"\n📌 Suggestions for {faculty_id}:\n")
    if len(weak)==0:
        print("✔ No improvements required. This faculty is performing well.")
    else:
        for dom in weak.index:
            print(f"⚠ {dom.replace('_',' ').title()} needs improvement")

faculty_suggestions("F104")

📌 Suggestions for F104:

✔ No improvements required. This faculty is performing well.

In [ ]:
print("\n🎯 TOTAL SUMMARY")
print("Number of Faculty:", df['faculty_id'].nunique())
print("Feedback Count   :", len(df))
print("Best Faculty      :", faculty_scores.idxmax())
print("Weakest Faculty   :", faculty_scores.idxmin())
print("Strongest Domain  :", avg_domain_scores.idxmax())
print("Weakest Domain    :", avg_domain_scores.idxmin())

🎯 TOTAL SUMMARY
Number of Faculty: 20
Feedback Count   : 2000
Best Faculty      : F103
Weakest Faculty   : F113
Strongest Domain  : interaction
Weakest Domain    : pace

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

summary_fig = make_subplots(
    rows=2, cols=3,
    specs=[[{"type": "indicator"}]*3,
           [{"type": "indicator"}]*3],
    subplot_titles=("Faculty Count", "Feedback Count", "Best Faculty",
                    "Weakest Faculty", "Strongest Domain", "Weakest Domain")
)

# 1 Faculty Count
summary_fig.add_trace(go.Indicator(
    mode="number",
    value=df['faculty_id'].nunique(),
    title="Number of Faculty",
    number={"font":{"size":40, "color":"#10b981"}}
), row=1, col=1)

# 2 Feedback Count
summary_fig.add_trace(go.Indicator(
    mode="number",
    value=len(df),
    title="Total Feedback Entries",
    number={"font":{"size":40, "color":"#3b82f6"}}
), row=1, col=2)

# 3 Best Faculty
summary_fig.add_trace(go.Indicator(
    mode="number+delta",
    value=faculty_scores.max(),
    delta={"reference":faculty_scores.min(), "increasing":{"color":"green"}},
    title=f"Best Faculty ({faculty_scores.idxmax()})",
    number={"font":{"size":40, "color":"#22c55e"}}
), row=1, col=3)

# 4 Weakest Faculty
summary_fig.add_trace(go.Indicator(
    mode="number+delta",
    value=faculty_scores.min(),
    delta={"reference":faculty_scores.max(), "decreasing":{"color":"red"}},
    title=f"Weakest Faculty ({faculty_scores.idxmin()})",
    number={"font":{"size":40, "color":"#ef4444"}}
), row=2, col=1)

# 5 Strongest Domain
strong_dom = avg_domain_scores.idxmax()
summary_fig.add_trace(go.Indicator(
    mode="number",
    value=avg_domain_scores.max(),
    title=f"Strongest Domain ({strong_dom.replace('_',' ').title()})",
    number={"font":{"size":40, "color":"#0ea5e9"}}
), row=2, col=2)

# 6 Weakest Domain
weak_dom = avg_domain_scores.idxmin()
summary_fig.add_trace(go.Indicator(
    mode="number",
    value=avg_domain_scores.min(),
    title=f"Weakest Domain ({weak_dom.replace('_',' ').title()})",
    number={"font":{"size":40, "color":"#f97316"}}
), row=2, col=3)

summary_fig.update_layout(height=700, width=1200, title_text="🔥 OVERALL FEEDBACK SUMMARY DASHBOARD")
summary_fig.show()

In [ ]:
suggestion_map = {
    "concept_explanation": "Improve clarity by breaking topics into smaller units and giving more structured explanations.",
    "real_life_examples": "Add more real-world examples and case studies to make concepts relatable.",
    "pace": "Try slowing down the teaching pace and pause after each concept for better understanding.",
    "doubt_handling": "Encourage more questions and allocate dedicated doubt-solving time.",
    "clarity": "Use board/PPT highlighting to improve clarity and avoid rushed explanations.",
    "language_clarity": "Improve pronunciation and reduce filler words for better comprehension.",
    "interaction": "Engage students through polls, questions, and small discussions.",
    "communication": "Focus on tone modulation and make communication more student-friendly.",
    "knowledge_depth": "Include advanced insights and practical scenarios to show deeper understanding.",
    "industry_relevance": "Connect topics to modern industry tools, trends, and technologies.",
    "updated_content": "Update lecture content to latest syllabus revision and new methodologies.",
    "time_management": "Maintain strict timing for topics and avoid spending too long on one part.",
    "discipline_control": "Strengthen classroom control by using positive reinforcement strategies.",
    "ppt_quality": "Improve PPT readability, reduce text, and add diagrams and flowcharts.",
    "assignment_quality": "Design assignments that are application-based and include real-world tasks."
}

In [ ]:
def generate_suggestions_for_faculty(faculty_id):
    fac = faculty_domain_avg.loc[faculty_id]
    weak_domains = fac[fac < 3.0]

    print(f"\n📝 AUTO-GENERATED IMPROVEMENT SUGGESTIONS FOR {faculty_id}:\n")

    if len(weak_domains) == 0:
        print("✔ All teaching domains are strong. No improvement required.")
        return

    for domain in weak_domains.index:
        print(f"⚠ {domain.replace('_',' ').title()}:")
        print("➡", suggestion_map[domain])
        print()

In [ ]:
generate_suggestions_for_faculty("F104")

📝 AUTO-GENERATED IMPROVEMENT SUGGESTIONS FOR F104:

✔ All teaching domains are strong. No improvement required.

In [ ]:
import plotly.graph_objects as go

def compare_faculty_domain(faculty_id):
    fac_scores = faculty_domain_avg.loc[faculty_id].values
    avg_scores = faculty_domain_avg.mean().values

    fig = go.Figure()

    # Faculty Line
    fig.add_trace(go.Scatter(
        x=domains,
        y=fac_scores,
        mode='lines+markers',
        name=f'{faculty_id} Scores',
        line=dict(color='green', width=4),
        marker=dict(size=8)
    ))

    # Institute Average Line
    fig.add_trace(go.Scatter(
        x=domains,
        y=avg_scores,
        mode='lines+markers',
        name='Institute Average',
        line=dict(color='blue', width=3, dash='dash'),
        marker=dict(size=8)
    ))

    fig.update_layout(
        title=f"📊 Domain-wise Comparison: {faculty_id} vs Institute Average",
        xaxis_title="Teaching Domains",
        yaxis_title="Rating",
        width=1200,
        height=500
    )

    fig.show()

# Example
compare_faculty_domain("F119")

In [ ]:
import pandas as pd
import numpy as np

# df is your feedback dataframe
# faculty_domain_avg is computed earlier
# domains list already exists

df_feedback = df.copy()   # rename for clarity

In [ ]:
# Calculate overall SD of ratings across all 15 domains
all_ratings = df_feedback[domains].values.flatten()

std_dev = np.std(all_ratings)
RSA = 1 - (std_dev / 5)

print("📌 Rating Stability Accuracy (RSA):", round(RSA * 100, 2), "%")

📌 Rating Stability Accuracy (RSA): 77.66 %

In [ ]:
def cronbach_alpha(df):
    df_scores = df[domains]
    item_vars = df_scores.var(axis=0, ddof=1)
    total_var = df_scores.sum(axis=1).var(ddof=1)
    k = df_scores.shape[1]
    alpha = (k / (k - 1)) * (1 - item_vars.sum() / total_var)
    return alpha

alpha = cronbach_alpha(df_feedback)
print("📌 Domain Reliability (Cronbach Alpha):", round(alpha * 100, 2), "%")

📌 Domain Reliability (Cronbach Alpha): -6.49 %

In [ ]:
faculty_scores = faculty_domain_avg.mean(axis=1)
inst_avg = faculty_scores.mean()

deviation = abs(faculty_scores - inst_avg).mean()
FEA = 1 - (deviation / 5)

print("📌 Faculty Evaluation Accuracy (FEA):", round(FEA * 100, 2), "%")

📌 Faculty Evaluation Accuracy (FEA): 99.51 %

In [ ]:
!pip install textblob
from textblob import TextBlob

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.1)

In [ ]:
def sentiment(text):
    if pd.isna(text) or text.strip() == "":
        return 0
    return TextBlob(text).sentiment.polarity

df_feedback["sentiment"] = df_feedback["feedback_comment"].apply(sentiment)

In [ ]:
aligned = 0

for _, row in df_feedback.iterrows():
    rat = np.mean([row[d] for d in domains])  # avg domain score
    sent = row["sentiment"]

    if sent > 0 and rat >= 3:     # positive comment ⇒ high rating
        aligned += 1
    elif sent < 0 and rat < 3:   # negative comment ⇒ low rating
        aligned += 1
    elif -0.1 <= sent <= 0.1 and 2.5 <= rat <= 3.5:  # neutral ⇒ mid rating
        aligned += 1

SRA = aligned / len(df_feedback)

print("📌 Sentiment–Rating Alignment Accuracy (SRA):", round(SRA * 100, 2), "%")

📌 Sentiment–Rating Alignment Accuracy (SRA): 70.0 %

In [ ]:
overall_accuracy = (RSA + alpha + FEA + SRA) / 4

print("\n🎯 OVERALL SYSTEM ACCURACY:", round(overall_accuracy * 100, 2), "%")

🎯 OVERALL SYSTEM ACCURACY: 60.17 %

## TECHNICAL ALGORITHM FOR FEEDBACK ANALYSIS

 **ALGORITHM NAME:**
***Faculty Feedback Multi-Domain Weighted Evaluation Algorithm (FF-MDWEA)***

 **INPUT:**

F = Set of faculty, size = N

S = Set of students, size = M

D = 15-domain rating vector per feedback

Rᵢⱼ = Rating given by student i to faculty j

Rᵢⱼ(d) = Rating of domain d for faculty j

 **OUTPUT:**

Faculty Performance Vector → FP(j)

Domain Strength Vector → DS(d)

Best/Weakest Faculty

Strongest/Weakest Domain

Visualization matrices (Heatmap, Radar, Summary Indicators)

 **ALGORITHM STEPS (Technical + Mathematical)**

**STEP 1 — Data Normalization**

Purpose: Remove bias between rating patterns.

For each domain d:

$R^*_{i,j,d} = \frac{R_{i,j,d} - \min(R_d)}{\max(R_d) - \min(R_d)}$

This converts ratings → normalized range [0,1].

If normalization unnecessary, skip step.

**STEP 2 — Domain Aggregation (Faculty-Level)**

For each faculty j, compute domain-wise mean:

$D_{avg}(j,d) = \frac{1}{M} \sum_{i=1}^{M} R_{i,j,d}$

Where

M = number of students who rated that faculty (100)

d = 1 to 15 domains

**STEP 3 — Weighted Faculty Score**

Each domain can have weight W(d) (optional).
(Default = equal → 1)

$FP(j) = \frac{\sum_{d=1}^{15} (D_{avg}(j,d) \times W(d))}{\sum_{d=1}^{15} W(d)}$

FP(j) = overall performance score of faculty j.

**STEP 4 — Domain Strength (Institute-Level)**

Calculate average domain performance across all faculties:

$DS(d) = \frac{1}{N} \sum_{j=1}^{N} D_{avg}(j,d)$

Where

N = number of faculty (20)

Higher DS(d) → stronger teaching domain
Lower DS(d) → weakest domain → training required

**STEP 5 — Ranking Algorithm**
Best Faculty:
$BestFaculty = \arg\max_{j \in F} FP(j)$